# Generated by Django 5.0.6 on 2024-07-14 16:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profiles/')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 7, 14, 22, 10, 12, 854741))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 7, 14, 22, 10, 12, 854741))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
