# Generated by Django 5.0.6 on 2024-07-15 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUsersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('profile_url', models.URLField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 7, 15, 22, 54, 19, 215216))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 7, 15, 22, 54, 19, 215216))),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 22, 54, 19, 214216)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 22, 54, 19, 214216)),
        ),
    ]
