# Generated by Django 5.0.6 on 2024-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_socialusersprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialusersprofile',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_url',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2012/04/26/19/43/profile-42914_640.png'),
        ),
    ]
