# Generated by Django 5.0.6 on 2024-07-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tag_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='upload_date',
        ),
    ]
