# Generated by Django 5.0.6 on 2024-07-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_document_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(max_length=500),
        ),
    ]
